### ISSUE TITLE
Logging out of an account

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/acebook-team-baddiez#12]
As a user,
So that I can share devices with my family,
I would like to be able to log out of my account.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to log out of my account](https://trello.com/c/SKETnEnK/16-i-would-like-to-log-out-of-my-account)

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to log out of my account](https://trello.com/c/SKETnEnK/16-i-would-like-to-log-out-of-my-account)
