### ISSUE TITLE
Have a profile page

### ISSUE THREAD

**Issue by heykathl** [adamwoodcock98/acebook-team-baddiez#14]
As a user,
So that other users can identify who I am and find out more information about me,
I would like to have a profile page.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to have a profile page](https://trello.com/c/A7FyRn2E/27-i-would-like-to-have-a-profile-page)

**Comment by adamwoodcock98** [comment]
Significant progress made on [this pull request](https://github.com/adamwoodcock98/acebook-team-baddiez/pull/61) (documented).
