### ISSUE TITLE
Cannot access content when not signed in

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/acebook-team-baddiez#15]
As an administrator,
So that I can keep my users safe,
I would like to prevent users that are not logged-in from accessing content.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to prevent access to non-logged-in users](https://trello.com/c/BnAeeblO/17-i-would-like-to-prevent-access-to-non-logged-in-users)

**Comment by adamwoodcock98** [comment]
Done.
