### ISSUE TITLE
Approve or deny friend request

### ISSUE THREAD

**Issue by heykathl** [adamwoodcock98/acebook-team-baddiez#16]
As user,
So that I can control who can interact with me,
I would approve or deny an incoming friend request.

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would approve or deny an incoming friend request](https://trello.com/c/hOaWrEXZ/29-i-would-approve-or-deny-an-incoming-friend-request)

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would approve or deny an incoming friend request](https://trello.com/c/hOaWrEXZ/29-i-would-approve-or-deny-an-incoming-friend-request)
