### ISSUE TITLE
Writing posts

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/acebook-team-baddiez#17]
As a user,
So that I can share updates with my friends,
I would like to be able to write posts.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to be able to write posts.](https://trello.com/c/VHgOxC7C/18-i-would-like-to-be-able-to-write-posts)

**Comment by adamwoodcock98** [comment]
Done.
