### ISSUE TITLE
Send a friend request

### ISSUE THREAD

**Issue by heykathl** [adamwoodcock98/acebook-team-baddiez#18]
As a user,
So that I can connect with my friends
I would like to send them a friend request

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to send them a friend request](https://trello.com/c/7CLlv1rL/35-i-would-like-to-send-them-a-friend-request)

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to send them a friend request](https://trello.com/c/7CLlv1rL/35-i-would-like-to-send-them-a-friend-request)

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to send them a friend request](https://trello.com/c/7CLlv1rL/35-i-would-like-to-send-them-a-friend-request)

**Comment by r94o** [comment]
feature complete
