### ISSUE TITLE
Sign up for an account 

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/acebook-team-baddiez#2]
As a person,
So that I can connect with my friends,
I would like to be able to sign up for an account.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to be able to sign up to an account](https://trello.com/c/A6P6B7se/13-i-would-like-to-be-able-to-sign-up-to-an-account)

**Comment by adamwoodcock98** [comment]
Done.
