### ISSUE TITLE
Viewing posts of others

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/acebook-team-baddiez#20]
As a user,
So that I can stay connected with my friends,
I would like to be able to view posts from other people.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to be able to view posts from other people.](https://trello.com/c/Li4fvKIN/31-i-would-like-to-be-able-to-view-posts-from-other-people)

**Comment by adamwoodcock98** [comment]
Done.
