### ISSUE TITLE
Display username and photo next to post

### ISSUE THREAD

**Issue by heykathl** [adamwoodcock98/acebook-team-baddiez#21]
As a user viewing another user’s post,
So that I know who posted,
I would like to see their username and photo next to the post.

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to see their username and photo next to the post](https://trello.com/c/rwui89jw/20-i-would-like-to-see-their-username-and-photo-next-to-the-post)
