### ISSUE TITLE
Adding a new user with an existing email crashes the server

### ISSUE THREAD

**Issue by PKilgarriff** [adamwoodcock98/acebook-team-baddiez#56]
# Steps to Reproduce

1. Navigate to users/new
2. Sign up with an email that already exists within the database (Use Table Plus)
3. Crash the server
4. Enjoy

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Server crashes whilst trying to sign up with an existing users email](https://trello.com/c/rdF1otXa/70-server-crashes-whilst-trying-to-sign-up-with-an-existing-users-email)

**Comment by PKilgarriff** [comment]
https://github.com/adamwoodcock98/acebook-team-baddiez/pull/66
