### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/acebook-team-baddiez#6]
As a user,
So that I know my personal information is secure,
I would like my password to be encrypted.

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to have an encrypted password](https://trello.com/c/VF4UeB7u/14-i-would-like-to-have-an-encrypted-password)

**Comment by adamwoodcock98** [comment]
Done.
